server:
  port: 8080  # default port


spring:
  application:
    name: rikky_takeaway  # 应用名称


  # 数据库信息|必填
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 本人将使用服务器启动项填写以下敏感信息 #
      # IDEA->Run->Edit Configurations->Environment Variables->添加以下变量 #
      url: # 请自行配置数据库url， e.g. jdbc:mysql://localhost:3306/rikkytakeaway?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: # 请自行配置数据库username
      password: # 本地测试时请自行添加password


  # 邮箱验证配置信息|必填
  mail:
    host: smtp.qq.com   # 如果你需要使用非qq邮箱，请自行配置host
    username: # 请自行配置邮箱地址
    password: wddrbljraesbdhdg # 请自行配置邮箱smtp授权码 具体请看本项目根目录下的README.md
    port: 587
    default-encoding: UTF-8
    timeout: 10 # 验证码有效时间 单位：分钟
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        # 开启debug以后，邮件发送过程的日志会在控制台上打印出来
        debug: true


  # redis缓存相关配置|必填
  redis:
    host: localhost
    port: 6379          # 默认端口
    password:           # 默认为空
    database: 0         # 默认使用0号数据库


# mybatis-plus配置信息
mybatis-plus:
  configuration:
    # 在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID


# 其它配置信息
rikky:
  # 文件存储位置信息|必填
  linux-path: C:\Users\river\code\work\javaProjects\rikky-takeaway\img\  # 本地测试时，文件存储路径，img的绝对路径，img后需要加上斜杠
#  windows-path: # !!!暂不使用，即使你是非linux系统，也在上方linux-path里配置存储地址
